xamarin/GoogleApisForiOSComponents

Google.Analytics/externals/Podfile
Google.AppIndexing/externals/Makefile
Google.AppIndexing/externals/Podfile
Google.AppInvite/externals/Makefile
Google.AppInvite/externals/Podfile
Google.Cast/externals/Makefile
Google.Cast/externals/Podfile
Google.Core/externals/Makefile
Google.Core/externals/Podfile
Google.GoogleCloudMessaging/externals/Makefile
Google.GoogleCloudMessaging/externals/Podfile
Google.InstanceID/externals/Makefile
Google.InstanceID/externals/Podfile
Google.Maps/externals/Makefile
Google.Maps/externals/Podfile
Google.MobileAds/externals/Podfile
Google.PlayGames/externals/Podfile
Google.SignIn/externals/Makefile
Google.SignIn/externals/Podfile
Google.TagManager/externals/Makefile
Google.TagManager/externals/Podfile

Updated Podfiles and Makefiles to support pod v1.x

Pod update

---

Google.Analytics/component/component.yaml
Google.Analytics/nuget/Xamarin.Google.iOS.Analytics.nuspec
Google.Analytics/source/Google.Analytics/Google.Analytics.targets

Check for the IsAppExtension property.

Need to consider iOS App extensions as well for Xamarin.Build.Download.

---

Firebase.Invites/component/component.yaml
Firebase.Invites/nuget/Xamarin.Firebase.iOS.Invites.nuspec
Google.SignIn/.gitignore
Google.SignIn/component/component.yaml
Google.SignIn/externals/Makefile
Google.SignIn/externals/Podfile
Google.SignIn/nuget/Xamarin.Google.iOS.SignIn.nuspec
Google.SignIn/samples/SignInExample/SignInExample/SignInExample.csproj
Google.SignIn/source/Google.SignIn/Google.SignIn.targets
Google.SignIn/source/Google.SignIn/GoogleSignIn.linkwith.cs

Reverts xamarin/GoogleApisForiOSComponents#47

Revert "Google Sign-In update to v4.0.1"

---

Firebase.AdMob/component/component.yaml
Firebase.AdMob/samples/AdMobSample/AdMobSample/AdMobSample.csproj
Firebase.Analytics/component/component.yaml
Firebase.Analytics/samples/AnalyticsSample/AnalyticsSample/AnalyticsSample.csproj
Firebase.Auth/component/component.yaml
Firebase.Auth/samples/AuthSample/AuthSample/AuthSample.csproj
Firebase.CloudMessaging/component/component.yaml
Firebase.CloudMessaging/samples/CloudMessagingSample/CloudMessagingSample/CloudMessagingSample.csproj
Firebase.Database/component/component.yaml
Firebase.Database/samples/DatabaseSample/DatabaseSample/DatabaseSample.csproj
Firebase.DynamicLinks/component/component.yaml
Firebase.DynamicLinks/samples/DynamicLinksSample/DynamicLinksSample/DynamicLinksSample.csproj
Firebase.Invites/component/component.yaml
Firebase.Invites/samples/InvitesSample/InvitesSample/InvitesSample.csproj
Firebase.RemoteConfig/component/component.yaml
Firebase.RemoteConfig/samples/RemoteConfigSample/RemoteConfigSample/RemoteConfigSample.csproj
Firebase.Storage/component/component.yaml
Firebase.Storage/samples/StorageSample/StorageSample/StorageSample.csproj
Google.TagManager/component/component.yaml
Google.TagManager/samples/TagManagerSample/TagManagerSample/TagManagerSample.csproj

[firebase] Unchecked Incremental builds option from samples in Debug|Simulator

Firebase - disable Incremental builds

---

Firebase.CrashReporting/component/component.yaml
Firebase.CrashReporting/nuget/Xamarin.Firebase.iOS.CrashReporting.nuspec
Firebase.CrashReporting/source/Firebase.CrashReporting/ApiDefinition.cs

* Added missing [Static] attribute in ApiDefinition

[Fix] Firebase Crash Reporting v2.0.0.2

---

Google.Cast/component/component.yaml
Google.Cast/externals/Podfile
Google.Cast/nuget/Xamarin.Google.iOS.Cast.nuspec
Google.Cast/source/Google.Cast/ApiDefinition.cs
Google.Cast/source/Google.Cast/Extensions.cs
Google.Cast/source/Google.Cast/Google.Cast.targets
Google.Cast/source/Google.Cast/StructsAndEnums.cs

- Branch based on @christianhelle contribution (Thank you!)
- This closes #101
- Added missing Properties, Methods and Attributes of most recent version
- Added missing Classes and Fields of previous versions (my bad...)

[Update] Google Cast v3.5.6

---

Google.Cast/component/component.yaml
Google.Cast/nuget/Xamarin.Google.iOS.Cast.nuspec
Google.Cast/samples/CastSample/CastSample/AppDelegate.cs
Google.Cast/samples/CastSample/CastSample/Info.plist
Google.Cast/source/Google.Cast/ApiDefinition.cs

[Google][Cast] Uncommented UIStyle.CastViews property

---

Firebase.AdMob/component/component.yaml
Firebase.AdMob/nuget/Xamarin.Firebase.iOS.AdMob.nuspec
Google.MobileAds/component/component.yaml
Google.MobileAds/nuget/Xamarin.Google.iOS.MobileAds.nuspec
Readme.md

* Bumped version due fix to avoid GADMediatedNativeAd duplicated symbol error.
* This fixes #146

[Fix] Firebase AdMob for iOS v7.27.0.3

---

Firebase.AdMob/component/component.yaml
Firebase.AdMob/nuget/Xamarin.Firebase.iOS.AdMob.nuspec
Google.MobileAds/component/component.yaml
Google.MobileAds/externals/Podfile
Google.MobileAds/nuget/Xamarin.Google.iOS.MobileAds.nuspec
Google.MobileAds/source/Google.MobileAds/ApiDefinition.cs
Readme.md

* Bumped Firebase.AdMob and Google.MobileAds versions
* Based on @ThomasDhaen fix (Thank you!)
* This closes PR #167 
* This closes issue #166

[Firebase][AdMob] Bumped version

---

Google.Cast/build.cake
Google.Cast/component/component.yaml
Google.Cast/externals/Podfile
Google.Cast/externals/Podfile.lock
Google.Cast/nuget/Xamarin.Google.iOS.Cast.nuspec
Google.Cast/samples/CastSample/CastSample.sln
Google.Cast/samples/CastSample/CastSample/CastSample.csproj
Google.Cast/source/Google.Cast/ApiDefinition.cs
Google.Cast/source/Google.Cast/Google.Cast.targets
Google.Cast/source/Google.Cast/Properties/AssemblyInfo.cs
Google.Cast/source/Google.Cast/StructsAndEnums.cs
Readme.md
poco.cake

* Based on @Obelobel contribution (Thank you!)
* This closes #184
* Updated the Readme.md file
* Reviewed the Podfile file
* Updated the ApiDefinition file
* Added new classes
* Removed `GCKUIStyleAttributes*` classes for now, symbols are private externals
* Reviewed the targets file
* Updated the AssemblyInfo file
* Google Cast now depends on Firebase Core

[Google][Cast] Updated to version 4.3.2

---

Firebase.Crashlytics/component/component.yaml
Firebase.Crashlytics/externals/Podfile
Firebase.Crashlytics/externals/Podfile.lock
Firebase.Crashlytics/nuget/Xamarin.Firebase.iOS.Crashlytics.nuspec
Firebase.Crashlytics/source/Firebase.Crashlytics/Firebase.Crashlytics.targets
Firebase.Crashlytics/source/Firebase.Crashlytics/Properties/AssemblyInfo.cs

[Update] Firebase Crashlytics for iOS v3.10.9

---

Google.TagManager/component/component.yaml
Google.TagManager/nuget/Xamarin.Google.iOS.TagManager.nuspec
Google.TagManager/source/Google.TagManager/Google.TagManager.targets

[Fix][Google][TagManager] Fixed resources path

---

build.cake

Added nuget validator to build.cake

---

Firebase.ABTesting/nuget/Xamarin.Firebase.iOS.ABTesting.nuspec
Firebase.AdMob/component/component.yaml
Firebase.AdMob/nuget/Xamarin.Firebase.iOS.AdMob.nuspec
Firebase.Analytics/component/component.yaml
Firebase.Analytics/nuget/Xamarin.Firebase.iOS.Analytics.nuspec
Firebase.Analytics/source/Firebase.Analytics/ApiDefinition.cs
Firebase.Analytics/source/Firebase.Analytics/Properties/AssemblyInfo.cs
Firebase.DynamicLinks/component/component.yaml
Firebase.DynamicLinks/nuget/Xamarin.Firebase.iOS.DynamicLinks.nuspec
Firebase.Invites/nuget/Xamarin.Firebase.iOS.Invites.nuspec
Firebase.PerformanceMonitoring/component/component.yaml
Firebase.PerformanceMonitoring/nuget/Xamarin.Firebase.iOS.PerformanceMonitoring.nuspec
Firebase.RemoteConfig/component/component.yaml
Firebase.RemoteConfig/nuget/Xamarin.Firebase.iOS.RemoteConfig.nuspec
Google.InstanceID/component/component.yaml
Google.InstanceID/nuget/Xamarin.Google.iOS.InstanceID.nuspec
Google.TagManager/component/component.yaml
Google.TagManager/nuget/Xamarin.Google.iOS.TagManager.nuspec
Readme.md

* Fixed a bug where passing null or an empty dictionary to LogEvent method crashes the app
* This closes #209

[Fix] Firebase Analytics v5.1.4.1

---

Firebase.Auth/component/component.yaml
Firebase.Auth/nuget/Xamarin.Firebase.iOS.Auth.nuspec
Firebase.Auth/source/Firebase.Auth/ApiDefinition.cs
Firebase.Auth/source/Firebase.Auth/Properties/AssemblyInfo.cs
Readme.md

* [Firebase][Auth] Fixed callback type on SignInWithCustomToken method
* This fixes #213

[Fix] Firebase Auth v5.0.4.1

---

Google.Cast/component/component.yaml
Google.Cast/nuget/Xamarin.Google.iOS.Cast.nuspec
Google.Cast/source/Google.Cast/ApiDefinition.cs
Google.Cast/source/Google.Cast/Extensions.cs
Google.Cast/source/Google.Cast/Google.Cast.targets
Google.Cast/source/Google.Cast/Properties/AssemblyInfo.cs
Google.Cast/source/Google.Cast/StructsAndEnums.cs
Readme.md

[Update] Google Cast for iOS v4.4.2

---

Readme.md
cgmanifest.json
components.cake
source/Firebase/PerformanceMonitoring/PerformanceMonitoring.csproj
source/Firebase/PerformanceMonitoring/PerformanceMonitoring.targets
source/Firebase/RemoteConfig/RemoteConfig.csproj
source/Firebase/RemoteConfig/RemoteConfig.targets

This PR updates the version of PerformanceMonitoring as well as its new dependency RemoteConfig to version 5.16.0 of Firebase.
The feature of sessions is now available in PerformanceMonitoring- the ability to examine anonymized sessions from the Firebase console.

Update PerformanceMonitoring to 5.16.0

---

components.cake
samples/Google/Cast/CastSample/CastSample.csproj
samples/Google/Cast/CastSample/Info.plist
source/Google/Cast/ApiDefinition.cs
source/Google/Cast/Cast.csproj
source/Google/Cast/Cast.props
source/Google/Cast/Cast.targets
source/Google/Cast/Enums.cs
source/Google/Cast/Loader.cs
source/Google/Cast/readme.txt

[Update] Google Cast for iOS v4.4.5

---

Readme.md
components.cake
samples/Firebase/Crashlytics/CrashlyticsSample/CrashlyticsSample.csproj
source/Firebase/Crashlytics/Crashlytics.csproj
source/Firebase/Crashlytics/Crashlytics.props
source/Firebase/Crashlytics/Crashlytics.targets
source/Firebase/Crashlytics/readme.txt

* Added a flag that handles the upload dSYM process, so the user can now decide if wants to execute the process
* Added a flag that handles the error, if any, of the upload process as a warning or as an error
* This closes issue #210
* This closes issue #275

[Update] Firebase Crashlytics for iOS v3.14.0

---

Readme.md
cgmanifest.json
components.cake
samples/Google/Places/GooglePlacesSample/GoogleApiKey.cs
source/Google/Maps/ApiDefinition.cs
source/Google/Maps/Maps.csproj
source/Google/Maps/Maps.targets
source/Google/Places/ApiDefinition.cs
source/Google/Places/Enums.cs
source/Google/Places/Places.csproj
source/Google/Places/Places.targets

[Update] Google Maps and Google Places for iOS v3.5.0

---

Readme.md
components.cake
source/Firebase/CloudMessaging/CloudMessaging.csproj

* This PR builds Firebase Cloud Messaging against Protobuf 3.8.0
* This fixes #311

[Fix] Firebase Cloud Messaging could not load protobuf.framework

---

Readme.md
components.cake
source/Firebase/Auth/ApiDefinition.cs
source/Firebase/Auth/Auth.csproj

* Fixed `SignInWithCredential` parameter type
* This fixes #326

[Fix] Firebase Auth v6.2.1.1  

---

SignList.xml
azure-pipelines.yml

"Upgrade" the signing process to the new, microbuild version.

Update signing to v2

---

global.json
source/Firebase/CloudMessaging/ApiDefinition.cs

[F.CloudMessaging] Fixed a wrong delegate type

---

azure-pipelines.yml
components.cake
global.json
source/Firebase/ABTesting/ABTesting.csproj
source/Firebase/AdMob/AdMob.csproj
source/Firebase/Analytics/Analytics.csproj
source/Firebase/Analytics/Analytics.targets
source/Firebase/Auth/Auth.csproj
source/Firebase/CloudFirestore/CloudFirestore.csproj
source/Firebase/CloudFunctions/CloudFunctions.csproj
source/Firebase/CloudMessaging/CloudMessaging.csproj
source/Firebase/Core/Core.csproj
source/Firebase/Core/Core.targets
source/Firebase/Crashlytics/Crashlytics.csproj
source/Firebase/Database/Database.csproj
source/Firebase/DynamicLinks/DynamicLinks.csproj
source/Firebase/InAppMessaging/InAppMessaging.csproj
source/Firebase/Installations/Installations.csproj
source/Firebase/PerformanceMonitoring/PerformanceMonitoring.csproj
source/Firebase/RemoteConfig/RemoteConfig.csproj
source/Firebase/Storage/Storage.csproj
source/Google/Analytics/Analytics.csproj
source/Google/Analytics/Analytics.targets
source/Google/MobileAds/MobileAds.csproj
source/Google/MobileAds/MobileAds.targets
source/Google/SignIn/SignIn.csproj
source/Google/SignIn/SignIn.targets
source/Google/TagManager/TagManager.csproj
source/Google/TagManager/TagManager.targets

* Added logic to strip bitcode from some closed-source Firebase/Google frameworks
* Now, frameworks are built using Xcode 14.0 which disables the bitcode by default
* Removed a workaround for G.MobileAds

Added logic to strip bitcode from closed-source frameworks

---

.ci/build.yml
azure-pipelines.yml

Context: https://github.com/xamarin/AndroidX/pull/658
We've been moving away from using one shared build template from the
`xamarin/XamarinComponents` repo.  A copy of that build template has
been moved to this repo and trimmed down to better represent the needs
of this build.  We can remove more conditions and clean up this build
template further in future PRs.
The CodeQL variables have been moved from the compliance pipeline into
the build pipeline as the compliance pipeline did not build any source.

[ci] Import build.yml from XamarinComponents
